# Generated by Django 5.2.2 on 2025-06-20 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_cita_options_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
