# Generated by Django 5.2.2 on 2025-08-22 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_paciente_genero_alter_paciente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('cancelada', 'cancelada'), ('finalizada', 'finalizada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha'), name='unique_medico_fecha'),
        ),
    ]
