# Generated by Django 5.2.5 on 2025-08-23 23:09

import agenda.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_cita_options_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', agenda.models.UserManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cita',
            name='unique_medico_fecha',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='cita',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default=datetime.time(23, 8, 46, 686762)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.medico'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.paciente'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='agenda.especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, default='sin-telefono', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('medico', 'fecha', 'hora')},
        ),
    ]
