# Generated by Django 5.2.5 on 2025-08-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_clean_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora'], 'permissions': (('access_consultorio', 'Puede acceder al panel de consultorio'),)},
        ),
    ]
