# Generated by Django 5.2.5 on 2025-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_cita_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'hora'], name='agenda_cita_fecha_8a47a5_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='agenda_cita_estado_a9a647_idx'),
        ),
    ]
