# Generated by Django 5.2.5 on 2025-08-28 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_cita_agenda_cita_fecha_8a47a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancel_motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
