name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django checks & migrate (sqlite)
        env:
          SECRET_KEY: dummy
          DEBUG: 'True'
          ALLOWED_HOSTS: '127.0.0.1,localhost'
        run: |
          python manage.py check
          python manage.py migrate --noinput
      - name: Run tests
        run: python manage.py test -v 2
